[package]
name = "gpx-stamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.9"
geoutils = "0.5.1"
gpx = "0.9.1"
svg = "0.13.1"
